#!/bin/bash

BACKUP_DIR=/mnt/backup/rsnapshot/daily.0/ostankin-hosting/home/vlad
TMP_DIR=$(mktemp -d)
trap "{ rm -rf $TMP_DIR; }" EXIT
sudo cp /root/.ssh/hosting_maintenance.pub "$TMP_DIR"

docker run --rm \
  -it \
  -v${PWD}:/work \
  -v${HOME}/.ssh/ostankin_ed25519:/root/.ssh/id_rsa:ro \
  -v${HOME}/.ssh/ostankin_ed25519.pub:/root/.ssh/user_key.pub:ro \
  -v${TMP_DIR}/hosting_maintenance.pub:/root/.ssh/maintenance_key.pub:ro \
  -v${BACKUP_DIR}:/backup:ro \
  -e ANSIBLE_HOST_KEY_CHECKING=false \
  ostankin/ansible \
  ansible-playbook -i inventory.yml ostankin-build.yml
